import Head from "next/head";

// components
import Header from "../components/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>NextFood food Ordering Webapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </>
  );
}
